package fr.solunea.thaleia.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import fr.solunea.thaleia.model.ContentTypeProperty;
import fr.solunea.thaleia.model.Locale;

/**
 * Class _ContentPropertyName was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContentPropertyName extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<ContentTypeProperty> CONTENT_TYPE_PROPERTY = Property.create("contentTypeProperty", ContentTypeProperty.class);
    public static final Property<Locale> LOCALE = Property.create("locale", Locale.class);

    protected String name;

    protected Object contentTypeProperty;
    protected Object locale;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setContentTypeProperty(ContentTypeProperty contentTypeProperty) {
        setToOneTarget("contentTypeProperty", contentTypeProperty, true);
    }

    public ContentTypeProperty getContentTypeProperty() {
        return (ContentTypeProperty)readProperty("contentTypeProperty");
    }

    public void setLocale(Locale locale) {
        setToOneTarget("locale", locale, true);
    }

    public Locale getLocale() {
        return (Locale)readProperty("locale");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "contentTypeProperty":
                return this.contentTypeProperty;
            case "locale":
                return this.locale;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "contentTypeProperty":
                this.contentTypeProperty = val;
                break;
            case "locale":
                this.locale = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.name);
        out.writeObject(this.contentTypeProperty);
        out.writeObject(this.locale);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.name = (String)in.readObject();
        this.contentTypeProperty = in.readObject();
        this.locale = in.readObject();
    }

}
