package fr.solunea.thaleia.model.auto;

import org.apache.cayenne.CayenneDataObject;

import fr.solunea.thaleia.model.Publication;

/**
 * Class _SuspendData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SuspendData extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String EMAIL_PROPERTY = "email";
    public static final String PUBLICATION_PROPERTY = "publication";

    public static final String ID_PK_COLUMN = "id";

    public void setData(String data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public String getData() {
        return (String)readProperty(DATA_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setPublication(Publication publication) {
        setToOneTarget(PUBLICATION_PROPERTY, publication, true);
    }

    public Publication getPublication() {
        return (Publication)readProperty(PUBLICATION_PROPERTY);
    }


}
