package fr.solunea.thaleia.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import fr.solunea.thaleia.model.ContentVersionTag;

/**
 * Class _Tag was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Tag extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> VALUE = Property.create("value", String.class);
    public static final Property<List<ContentVersionTag>> CONTENT_VERSIONS = Property.create("contentVersions", List.class);

    protected String value;

    protected Object contentVersions;

    public void setValue(String value) {
        beforePropertyWrite("value", this.value, value);
        this.value = value;
    }

    public String getValue() {
        beforePropertyRead("value");
        return this.value;
    }

    public void addToContentVersions(ContentVersionTag obj) {
        addToManyTarget("contentVersions", obj, true);
    }

    public void removeFromContentVersions(ContentVersionTag obj) {
        removeToManyTarget("contentVersions", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ContentVersionTag> getContentVersions() {
        return (List<ContentVersionTag>)readProperty("contentVersions");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "value":
                return this.value;
            case "contentVersions":
                return this.contentVersions;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "value":
                this.value = (String)val;
                break;
            case "contentVersions":
                this.contentVersions = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.value);
        out.writeObject(this.contentVersions);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.value = (String)in.readObject();
        this.contentVersions = in.readObject();
    }

}
